### ISSUE TITLE
Раздел с настройками

### ISSUE THREAD

**Issue by kotleni** [dmitrijkotov634/android-bomber#13]
Нету нормального закрытия раздела с настройками, только системный возврат обратно.
**Добавьте крестик что-ли.**

**Comment by dmitrijkotov634** [comment]
В чем проблема нажимать кнопка назад на устройстве?

**Comment by kotleni** [comment]
Это не всем удобно.

**Comment by dmitrijkotov634** [comment]
Кому например?
