### ISSUE TITLE
Максимальное количество повторов

### ISSUE THREAD

**Issue by i1lya** [dmitrijkotov634/android-bomber#23]
Почему максимальное число количества повторов должно иметь только два символа ?
![IMG_20220202_171519](https://user-images.githubusercontent.com/86829363/152182668-f85d133e-6dc7-4cde-aaca-0efa3b67b7a2.jpg)

**Comment by dmitrijkotov634** [comment]
@i1lya Потому что использовать больше 10 повторов не имеет какого то смысла, если тебе надо больше 99 повторов, то запусти по очереди несколько атак.
